config/routes.rb
Rails.application.routes.draw do
  resources :towers
  resources :podia
  resources :pricings
  resources :apartments
  resources :gparameters
  resources :salesmatrices
  match 'ap' => 'apartments#temp', via: [:get, :post]
  match 'del_all' => 'podia#del_all', via: [:get, :post]
  match 'del_all' => 'towers#del_all', via: [:get, :post]

root 'salesmatrices#new'

end

app/models/gparameter.rb
class Gparameter < ActiveRecord::Base
    
    attr_writer :current_step
    before_save :def_val
  before_validation :def_val
  
  def def_val
    self.podium ||= 0
    self.tower ||= 1
    self.height_categories ||= 0
    self.wiev_aspects ||= 0
    self.studio ||= 0
    self.bed1 ||= 0
    self.bed2 ||= 0
    self.bed3 ||= 0
    self.bed4 ||= 0
    self.sub_ph ||= 0
    self.ph ||= 0
    self.other ||= 0
  end
  
    
  def current_step
    @current_step || steps.first
  end
  
  def steps
    %w[storeys variaties outline]
  end
  
  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end
  
  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end
  
  def first_step?
    current_step == steps.first
  end
  
  def last_step?
    current_step == steps.last
  end
    
    def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end
  
  validates_inclusion_of  :podium, :in => 0..100, :message => "Value must be beetween 0 - 100!"
  validates_inclusion_of  :tower, :in => 0..100, :message => "Value must be beetween 0 - 100!"
  validates_inclusion_of  :height_categories, :in => 0..4, :message => "Value must be beetween 0 - 100!"
  validates_inclusion_of  :studio, :in => 0..50, :message => "Value must be beetween 0 - 50!"
  validates_inclusion_of  :bed1, :in => 0..50, :message => "Value must be beetween 0 - 50!"
  validates_inclusion_of  :bed2, :in => 0..50, :message => "Value must be beetween 0 - 50!"
  validates_inclusion_of  :bed3, :in => 0..50, :message => "Value must be beetween 0 - 50!"
  validates_inclusion_of  :bed4, :in => 0..50, :message => "Value must be beetween 0 - 50!"
  validates_inclusion_of  :sub_ph, :in => 0..50, :message => "Value must be beetween 0 - 50!"
  validates_inclusion_of  :ph, :in => 0..50, :message => "Value must be beetween 0 - 50!"
  validates_inclusion_of  :other, :in => 0..50, :message => "Value must be beetween 0 - 50!"


end

app/controllers/gparameters_controller.rb
class GparametersController < ApplicationController
  before_action :set_gparameter, only: [:show, :edit, :update, :destroy]

  # GET /gparameters
  # GET /gparameters.json
  def index
    @gparameters = Gparameter.all
  end

  # GET /gparameters/1
  # GET /gparameters/1.json
  def show
  end

  # GET /gparameters/new
  def new
    session[:gparameter_params] ||= {}
    @gparameter = Gparameter.new(session[:gparameter_params])
    @gparameter.current_step = session[:gparameter_step]
  end

  # GET /gparameters/1/edit
  def edit
  end

  # POST /gparameters
  # POST /gparameters.json
  def create
    session[:gparameter_params].deep_merge!(params[:gparameter]) if params[:gparameter]
    @gparameter = Gparameter.new(session[:gparameter_params])
    @gparameter.current_step = session[:gparameter_step]
    if @gparameter.valid?
      if params[:back_button]
        @gparameter.previous_step
      elsif @gparameter.last_step?
        @gparameter.save if @gparameter.all_valid?
      else
        @gparameter.next_step
      end
      session[:gparameter_step] = @gparameter.current_step
    end
    if @gparameter.new_record?
      render "new"
    else
      session[:gparameter_step] = session[:gparameter_params] = nil
      #flash[:notice] = "XXXXXXX!"
      redirect_to ap_path
    end
  end

  # PATCH/PUT /gparameters/1
  # PATCH/PUT /gparameters/1.json
  def update
    respond_to do |format|
      if @gparameter.update(gparameter_params)
        format.html { redirect_to @gparameter, notice: 'Gparameter was successfully updated.' }
        format.json { render :show, status: :ok, location: @gparameter }
      else
        format.html { render :edit }
        format.json { render json: @gparameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gparameters/1
  # DELETE /gparameters/1.json
  def destroy
    @gparameter.destroy
    respond_to do |format|
      format.html { redirect_to gparameters_url, notice: 'Gparameter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gparameter
      @gparameter = Gparameter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gparameter_params
      params.require(:gparameter).permit(:podium, :tower, :total, :studio, :bed1, :bed2, :bed3, :bed4, :sub_ph, :ph, :other, :height_categories, :wiev_aspects)
    end
end

app/helpers/gparameters_helper.rb
module GparametersHelper
    
    def set_prices
    if Gparameter.first.present?
    va=Gparameter.first.wiev_aspects
    hk=Gparameter.first.height_categories 
    i=1
    while i<=hk do
        if i<=va
        Pricing.create(:height_pr  => 0, :aspect_pr => 0)
        else
        Pricing.create(:height_pr  => 0)
        end
    i=i+1
    end
    while i<=va do
    Pricing.create( :aspect_pr => 0)
    
    i=i+1
    end

        end
     end
end

app/views/gparameters/_form.html.erb
<%= form_for(@gparameter) do |f| %>
  <% if @gparameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gparameter.errors.count, "error") %> prohibited this gparameter from being saved:</h2>

      <ul>
      <% @gparameter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= render "#{@gparameter.current_step}_step", :f => f %>
  <p><%= f.submit "Continue" %></p>
  <p><%= f.submit "Back", :name => "back_button" unless @gparameter.first_step? %></p>


<% end %>

app/views/gparameters/_outline_step.html.erb
<div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
         <h4>Please Outline View Multiplier Categories</h4>
        </div>
        <div class="panel-body">

          <div class="field">
            <%= f.label :height_categories %><br>
            <%= f.number_field :height_categories %>
          </div>
          <div class="field">
            <%= f.label :wiev_aspects %><br>
            <%= f.number_field :wiev_aspects %>
          </div>
          </div>
         
      </div>
    </div>
  </div>

app/views/gparameters/_storeys_step.html.erb
<div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
            <h4>How Many Storeys in Building?</h4>
        </div>
        <div class="panel-body">



  <div class="field">
    <%= f.label :podium %><br>
    <%= f.number_field :podium %>
  </div>
  <div class="field">
    <%= f.label :tower %><br>
    <%= f.number_field :tower %>
  </div>
  <!--<div class="field">-->
  <!--  <%= f.label :total %><br>-->
  <!--  <%= f.number_field :total %>-->
  <!--</div>-->
  </div>
      </div>
    </div>
  </div>

app/views/gparameters/_variaties_step.html.erb
<div class="row">
    <div class="col-md-6 col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
           <h4>How Many Varieties of Each Unit Below?</h4>
        </div>
        <div class="panel-body">




  <div class="field">
    <%= f.label :studio %><br>
    <%= f.number_field :studio %>
  </div>
  <div class="field">
    <%= f.label :bed1 %><br>
    <%= f.number_field :bed1 %>
  </div>
  <div class="field">
    <%= f.label :bed2 %><br>
    <%= f.number_field :bed2 %>
  </div>
  <div class="field">
    <%= f.label :bed3 %><br>
    <%= f.number_field :bed3 %>
  </div>
  <div class="field">
    <%= f.label :bed4 %><br>
    <%= f.number_field :bed4 %>
  </div>
  <div class="field">
    <%= f.label :sub_ph %><br>
    <%= f.number_field :sub_ph %>
  </div>
  <div class="field">
    <%= f.label :ph %><br>
    <%= f.number_field :ph %>
  </div>
  <div class="field">
    <%= f.label :other %><br>
    <%= f.number_field :other %>
  </div>
  
  </div>
      </div>
    </div>
  </div>

app/views/gparameters/edit.html.erb
<h1>Editing Gparameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @gparameter %> |
<%= link_to 'Back', gparameters_path %>

app/views/gparameters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gparameters</h1>

<table>
  <thead>
    <tr>
      <th>Podium</th>
      <th>Tower</th>
      <th>Total</th>
      <th>Studio</th>
      <th>Bed1</th>
      <th>Bed2</th>
      <th>Bed3</th>
      <th>Bed4</th>
      <th>Sub ph</th>
      <th>Ph</th>
      <th>Other</th>
      <th>Height categories</th>
      <th>Wiev aspects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gparameters.each do |gparameter| %>
      <tr>
        <td><%= gparameter.podium %></td>
        <td><%= gparameter.tower %></td>
        <td><%= gparameter.total %></td>
        <td><%= gparameter.studio %></td>
        <td><%= gparameter.bed1 %></td>
        <td><%= gparameter.bed2 %></td>
        <td><%= gparameter.bed3 %></td>
        <td><%= gparameter.bed4 %></td>
        <td><%= gparameter.sub_ph %></td>
        <td><%= gparameter.ph %></td>
        <td><%= gparameter.other %></td>
        <td><%= gparameter.height_categories %></td>
        <td><%= gparameter.wiev_aspects %></td>
        <td><%= link_to 'Show', gparameter %></td>
        <td><%= link_to 'Edit', edit_gparameter_path(gparameter) %></td>
        <td><%= link_to 'Destroy', gparameter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gparameter', new_gparameter_path %>

app/views/gparameters/new.html.erb
<%= render 'form' %>

app/views/gparameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Podium:</strong>
  <%= @gparameter.podium %>
</p>

<p>
  <strong>Tower:</strong>
  <%= @gparameter.tower %>
</p>

<p>
  <strong>Total:</strong>
  <%= @gparameter.total %>
</p>

<p>
  <strong>Studio:</strong>
  <%= @gparameter.studio %>
</p>

<p>
  <strong>Bed1:</strong>
  <%= @gparameter.bed1 %>
</p>

<p>
  <strong>Bed2:</strong>
  <%= @gparameter.bed2 %>
</p>

<p>
  <strong>Bed3:</strong>
  <%= @gparameter.bed3 %>
</p>

<p>
  <strong>Bed4:</strong>
  <%= @gparameter.bed4 %>
</p>

<p>
  <strong>Sub ph:</strong>
  <%= @gparameter.sub_ph %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @gparameter.ph %>
</p>

<p>
  <strong>Other:</strong>
  <%= @gparameter.other %>
</p>

<p>
  <strong>Height categories:</strong>
  <%= @gparameter.height_categories %>
</p>

<p>
  <strong>Wiev aspects:</strong>
  <%= @gparameter.wiev_aspects %>
</p>

<%= link_to 'Edit', edit_gparameter_path(@gparameter) %> |
<%= link_to 'Back', gparameters_path %>