config/routes.rb
Rails.application.routes.draw do
  resources :towers
  resources :podia
  resources :pricings
  resources :apartments
  resources :gparameters
  resources :salesmatrices
  match 'ap' => 'apartments#temp', via: [:get, :post]
  match 'del_all' => 'podia#del_all', via: [:get, :post]
  match 'del_all' => 'towers#del_all', via: [:get, :post]

root 'salesmatrices#new'

end

app/models/tower.rb
class Tower < ActiveRecord::Base
end

app/controllers/towers_controller.rb
class TowersController < ApplicationController
  before_action :set_tower, only: [:show, :edit, :update, :destroy]

  # GET /towers
  # GET /towers.json
  def index
    @towers = Tower.all
  end

  # GET /towers/1
  # GET /towers/1.json
  def show
  end

  # GET /towers/new
  def new
    @tower = Tower.create
    flash[:notice] = "New layout was successfully created."
    redirect_to(:action => 'index')
  end
  
   def del_all
  Tower.delete_all
  flash[:notice] = "All Layouts deleted!"
  redirect_to(:action => 'index')
  end

  # GET /towers/1/edit
  def edit
  end

  # POST /towers
  # POST /towers.json
  def create
    @tower = Tower.new(tower_params)

    respond_to do |format|
      if @tower.save
        format.html { redirect_to @tower, notice: 'Tower was successfully created.' }
        format.json { render :show, status: :created, location: @tower }
      else
        format.html { render :new }
        format.json { render json: @tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /towers/1
  # PATCH/PUT /towers/1.json
  def update
    respond_to do |format|
      if @tower.update(tower_params)
        format.html { redirect_to @tower, notice: 'Tower was successfully updated.' }
        format.json { render :show, status: :ok, location: @tower }
      else
        format.html { render :edit }
        format.json { render json: @tower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towers/1
  # DELETE /towers/1.json
  def destroy
    @tower.destroy
    respond_to do |format|
      format.html { redirect_to towers_url, notice: 'Tower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tower
      @tower = Tower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tower_params
      params.require(:tower).permit(:apt1, :apt2, :apt3, :apt4, :apt5, :apt6, :apt7, :apt8, :apt9, :apt10, :apt11, :apt12, :apt13, :apt14, :apt15, :apt16, :apt17, :apt18, :apt19, :apt20)
    end
end

app/helpers/towers_helper.rb
module TowersHelper
    def types2
      @apt_types2=Apartment.all
      @r2= [[""]]
      @apt_types2.each do |apt_type|
         @r2= @r2+[[apt_type.apartmentID, apt_type.apartmentID]]
    
        end
    end
  
  def areaa2(row, j)
      @pod2=Tower.all
      apt="apt"+j.to_s
      @ap2=Apartment.where("apartmentID ='#{@pod2[row].send(apt)}'")
          
          if @ap2.present?
            @app2=@ap2.first.internal_area
            @type2=@ap2.first.apartmentID
            @bedrooms2=@ap2.first.bedrooms.to_s+ " bed".pluralize(@ap2.first.bedrooms)
            @carbays2=@ap2.first.carbays.to_s+" carbay".pluralize(@ap2.first.carbays)if @ap2.first.carbays.present?
          else
             @app2=""
             @type2=""
             @bedrooms2=""
             @carbays2=""
          end
        @a2=@pod2[row]  
       @num2=@a2.attributes.values.select(&:present?).count
        
  
  end
  
 
end

app/views/towers/_form.html.erb
<%= form_for(@tower) do |f| %>
  <% if @tower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tower.errors.count, "error") %> prohibited this tower from being saved:</h2>

      <ul>
      <% @tower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apt1 %><br>
    <%= f.text_field :apt1 %>
  </div>
  <div class="field">
    <%= f.label :apt2 %><br>
    <%= f.text_field :apt2 %>
  </div>
  <div class="field">
    <%= f.label :apt3 %><br>
    <%= f.text_field :apt3 %>
  </div>
  <div class="field">
    <%= f.label :apt4 %><br>
    <%= f.text_field :apt4 %>
  </div>
  <div class="field">
    <%= f.label :apt5 %><br>
    <%= f.text_field :apt5 %>
  </div>
  <div class="field">
    <%= f.label :apt6 %><br>
    <%= f.text_field :apt6 %>
  </div>
  <div class="field">
    <%= f.label :apt7 %><br>
    <%= f.text_field :apt7 %>
  </div>
  <div class="field">
    <%= f.label :apt8 %><br>
    <%= f.text_field :apt8 %>
  </div>
  <div class="field">
    <%= f.label :apt9 %><br>
    <%= f.text_field :apt9 %>
  </div>
  <div class="field">
    <%= f.label :apt10 %><br>
    <%= f.text_field :apt10 %>
  </div>
  <div class="field">
    <%= f.label :apt11 %><br>
    <%= f.text_field :apt11 %>
  </div>
  <div class="field">
    <%= f.label :apt12 %><br>
    <%= f.text_field :apt12 %>
  </div>
  <div class="field">
    <%= f.label :apt13 %><br>
    <%= f.text_field :apt13 %>
  </div>
  <div class="field">
    <%= f.label :apt14 %><br>
    <%= f.text_field :apt14 %>
  </div>
  <div class="field">
    <%= f.label :apt15 %><br>
    <%= f.text_field :apt15 %>
  </div>
  <div class="field">
    <%= f.label :apt16 %><br>
    <%= f.text_field :apt16 %>
  </div>
  <div class="field">
    <%= f.label :apt17 %><br>
    <%= f.text_field :apt17 %>
  </div>
  <div class="field">
    <%= f.label :apt18 %><br>
    <%= f.text_field :apt18 %>
  </div>
  <div class="field">
    <%= f.label :apt19 %><br>
    <%= f.text_field :apt19 %>
  </div>
  <div class="field">
    <%= f.label :apt20 %><br>
    <%= f.text_field :apt20 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towers/_table.html.erb
<div class="table-responsive">
    <% @towers.each_with_index do |tower, i| %>                            
                                <table class="table table-striped table-bordered table-hover podtable">
 <% if i==0 then %>
 
  <thead>
    <tr>
      <th></th>
      <th>Layout</th>
      <th>Categories</th>
      <th>Apt1</th>
      <th>apt2</th>
      <th>Apt3</th>
      <th>Apt4</th>
      <th>Apt5</th>
      <th>Apt6</th>
      <th>Apt7</th>
      <th>Apt8</th>
      <th>Apt9</th>
      <th>Apt10</th>
      <th>Apt11</th>
      <th>Apt12</th>
      <th>Apt13</th>
      <th>Apt14</th>
      <th>Apt15</th>
      <th>Apt16</th>
      <th>Apt17</th>
      <th>Apt18</th>
      <th>Apt19</th>
      <th>Apt20</th>
    
    </tr>
  </thead>
  
  <% else %>

  
  <% end %>

  <tbody>
    
      <tr>
       <td rowspan="5"><%= link_to "<button>Delete Layout</button>".html_safe, tower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td rowspan="5"><% j=1  %><% areaa2(i, j) %>Tower Layout <%= i+1 %> <br> <%= @num2-3 %> plate</td>
        <td>Name</td>
        <td><%=best_in_place tower, :apt1, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt2, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt3, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt4, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt5, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt6, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt7, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt8, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt9, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt10, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt11, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt12, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt13, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt14, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt15, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt16, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt17, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt18, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt19, type: :select, :collection => @r2 %></td>
        <td><%=best_in_place tower, :apt20, type: :select, :collection => @r2 %></td>
       
        
      </tr>
      
      <tr>
          
        <td>Type</td>
         <% j=1  %>
             <% until j>20  %>
              <td><% areaa2(i, j) %><%= @type2 %></td>
            <% j=j+1 %>
            <% end %>
        
      </tr>
      
      
      <tr>
          
            <td>Area</td>
             <% j=1  %>
             <% until j>20  %>
              <td><% areaa2(i, j) %><%= @app2 %></td>
            <% j=j+1 %>
            <% end %>
      </tr>
      <tr>
          
        <td>Bed</td>
         <% j=1  %>
             <% until j>20  %>
              <td><% areaa2(i, j) %><%= @bedrooms2 %></td>
            <% j=j+1 %>
            <% end %>
        
      </tr>
      <tr>
          
        <td>Carbays</td>
         <% j=1  %>
             <% until j>20  %>
              <td><% areaa2(i, j) %><%= @carbays2 %></td>
            <% j=j+1 %>
            <% end %>
        
      </tr>
      
      
      </tbody>
</table>
    <% end %>
  
</div>

app/views/towers/edit.html.erb
<h1>Editing Tower</h1>

<%= render 'form' %>

<%= link_to 'Show', @tower %> |
<%= link_to 'Back', towers_path %>

app/views/towers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-success">
<% types2 %>

              <div class="panel-heading">
                            TOWER FLOORPLATES
                        </div>
                        <div class="panel-body">
                          
                          <%= render 'table' %>
                            
</div>
</div>

<br>
<button onclick="myFunction()">Update Table</button>
<%= link_to "<button>Create new Layout</button>".html_safe, new_tower_path %>
<%= link_to "<button>Delete all Layouts</button>".html_safe, del_all_path %>


<script>
function myFunction() {
    location.reload();
}
</script>

app/views/towers/new.html.erb
<h1>New Tower</h1>

<%= render 'form' %>

<%= link_to 'Back', towers_path %>

app/views/towers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apt1:</strong>
  <%= @tower.apt1 %>
</p>

<p>
  <strong>Apt2:</strong>
  <%= @tower.apt2 %>
</p>

<p>
  <strong>Apt3:</strong>
  <%= @tower.apt3 %>
</p>

<p>
  <strong>Apt4:</strong>
  <%= @tower.apt4 %>
</p>

<p>
  <strong>Apt5:</strong>
  <%= @tower.apt5 %>
</p>

<p>
  <strong>Apt6:</strong>
  <%= @tower.apt6 %>
</p>

<p>
  <strong>Apt7:</strong>
  <%= @tower.apt7 %>
</p>

<p>
  <strong>Apt8:</strong>
  <%= @tower.apt8 %>
</p>

<p>
  <strong>Apt9:</strong>
  <%= @tower.apt9 %>
</p>

<p>
  <strong>Apt10:</strong>
  <%= @tower.apt10 %>
</p>

<p>
  <strong>Apt11:</strong>
  <%= @tower.apt11 %>
</p>

<p>
  <strong>Apt12:</strong>
  <%= @tower.apt12 %>
</p>

<p>
  <strong>Apt13:</strong>
  <%= @tower.apt13 %>
</p>

<p>
  <strong>Apt14:</strong>
  <%= @tower.apt14 %>
</p>

<p>
  <strong>Apt15:</strong>
  <%= @tower.apt15 %>
</p>

<p>
  <strong>Apt16:</strong>
  <%= @tower.apt16 %>
</p>

<p>
  <strong>Apt17:</strong>
  <%= @tower.apt17 %>
</p>

<p>
  <strong>Apt18:</strong>
  <%= @tower.apt18 %>
</p>

<p>
  <strong>Apt19:</strong>
  <%= @tower.apt19 %>
</p>

<p>
  <strong>Apt20:</strong>
  <%= @tower.apt20 %>
</p>

<%= link_to 'Edit', edit_tower_path(@tower) %> |
<%= link_to 'Back', towers_path %>