config/routes.rb
Rails.application.routes.draw do
  resources :towers
  resources :podia
  resources :pricings
  resources :apartments
  resources :gparameters
  resources :salesmatrices
  match 'ap' => 'apartments#temp', via: [:get, :post]
  match 'del_all' => 'podia#del_all', via: [:get, :post]
  match 'del_all' => 'towers#del_all', via: [:get, :post]

root 'salesmatrices#new'

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
    
    before_save :set_total_area
before_save :def_val
  before_validation :def_val
  
  def def_val
    self.bathrooms ||= 0
    self.study ||= 0
    self.carbays ||= 0
  end
 
  def set_total_area
 unless !self.internal_area.nil?
 self.internal_area=0
 end
 unless !self.balcony_area.nil?
 self.balcony_area=0
 end
    self.total_area = self.internal_area+self.balcony_area

  end
    validates_inclusion_of  :bathrooms, :in => 0..10, :message => "Value must be beetween 0 - 10!"
    validates_inclusion_of  :study, :in => 0..5, :message => "Value must be beetween 0 - 5!"
    validates_inclusion_of  :carbays, :in => 0..10, :message => "Value must be beetween 0 - 10!"
      
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def temp
   
    
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:apartmentID, :apartment_type, :name, :internal_area, :balcony_area, :total_area, :bedrooms, :bathrooms, :study, :carbays, :base_price, :colour)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
    
   
  
    
    def delete_old_data2
        Apartment.delete_all
    end
    
     def getdataapartment
        
        @studio=Gparameter.last.studio
        @bed1=Gparameter.last.bed1
        @bed2=Gparameter.last.bed2
        @bed3=Gparameter.last.bed3
        @bed4=Gparameter.last.bed4
        @sub_ph=Gparameter.last.sub_ph
        @ph=Gparameter.last.ph
        @other=Gparameter.last.other
        
        @ap_name=[]
        @ap_bedrooms=[]
        @ap_type=[]
        
        unless @studio.nil?
        if @studio>0 then
            i=0
            @studio.times do |i|
             i=i+1   
            @ap_name=@ap_name+["Studio ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[1]
            @ap_type=@ap_type+["Studio"]
            end
            end
         end
        unless @bed1.nil? 
        if @bed1>0 then
            i=0
            @bed1.times do |i|
             i=i+1   
            @ap_name=@ap_name+["1 Bed ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[1]
            @ap_type=@ap_type+["1 Bed"]
            end
        end
    end
        unless @bed2.nil? 
        if @bed2>0 then
            i=0
            @bed2.times do |i|
             i=i+1   
            @ap_name=@ap_name+["2 Bed ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[2]
            @ap_type=@ap_type+["2 Bed"]
            end
        end
    end
    unless @bed3.nil? 
        if @bed3>0 then
            i=0
            @bed3.times do |i|
             i=i+1   
            @ap_name=@ap_name+["3 Bed ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[3]
            @ap_type=@ap_type+["3 Bed"]
            end
        end
    end
    unless @bed4.nil? 
        if @bed4>0 then
            i=0
            @bed4.times do |i|
             i=i+1   
            @ap_name=@ap_name+["4 Bed ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[4]
            @ap_type=@ap_type+["4 Bed"]
            end
        end
    end
    unless @sub_ph.nil? 
        if @sub_ph>0 then
            i=0
            @sub_ph.times do |i|
             i=i+1   
            @ap_name=@ap_name+["Sub-Penthouse ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[3]
            @ap_type=@ap_type+["Sub-Penthouse"]
            end
        end
    end
    unless @ph.nil? 
        if @ph>0 then
            i=0
            @ph.times do |i|
             i=i+1   
            @ap_name=@ap_name+["Penthouse ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[3]
            @ap_type=@ap_type+["Penthouse"]
            end
        end
    end
    unless @other.nil? 
        if @other>0 then
            i=0
            @other.times do |i|
             i=i+1   
            @ap_name=@ap_name+["Other ##{i}"]
            @ap_bedrooms=@ap_bedrooms+[2]
            @ap_type=@ap_type+["Other"]
            end
        end
        
    end
    saver
end
    

    
    
    
    def saver
        Apartment.transaction do
        @ap_name.zip(@ap_bedrooms, @ap_type).each do |name, bedroom, type|
            @a_name = Apartment.create(:apartmentID => name, :apartment_type => type, :name => name, :bedrooms => bedroom)
            @a_name.save
            end
         end 
        
        
        
        
        end
    
    
 end
    

    

app/views/apartments/_form.html.erb
<%= form_for(@apartment) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apartmentID %><br>
    <%= f.text_field :apartmentID %>
  </div>
  <div class="field">
    <%= f.label :apartment_type %><br>
    <%= f.text_field :apartment_type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :internal_area %><br>
    <%= f.text_field :internal_area %>
  </div>
  <div class="field">
    <%= f.label :balcony_area %><br>
    <%= f.text_field :balcony_area %>
  </div>
  <div class="field">
    <%= f.label :total_area %><br>
    <%= f.text_field :total_area %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.text_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.text_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :study %><br>
    <%= f.text_field :study %>
  </div>
  <div class="field">
    <%= f.label :carbays %><br>
    <%= f.text_field :carbays %>
  </div>
  <div class="field">
    <%= f.label :base_price %><br>
    <%= f.text_field :base_price %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>
 <% set_prices %>

<div class="panel panel-success">

              <div class="panel-heading">
                            APARTMENT SPECS
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                
                                <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Apartmentid</th>
      <th>Apartment type</th>
      <th>Name</th>
      <th>Internal area</th>
      <th>Balcony area</th>
      <th>Total area</th>
      <th>Bedrooms</th>
      <th>Bathrooms</th>
      <th>Study</th>
      <th>Carbays</th>
      <th>Base price</th>
      <th>Colour</th>
      
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.apartmentID %></td>
   
        <td><%= apartment.apartment_type %></td>
        <td><%= best_in_place apartment, :name, :as => :input %></td>
        <td><%= best_in_place apartment, :internal_area, :as => :input %></td>
        <td><%= best_in_place apartment, :balcony_area, :as => :input %></td>
        <td><%= apartment.total_area %></td>
        <td><%= best_in_place apartment, :bedrooms, :as => :input %></td>
        <td><%= best_in_place apartment, :bathrooms, :as => :input %></td>
        <td><%= best_in_place apartment, :study, :as => :input %></td>
        <td><%= best_in_place apartment, :carbays, :as => :input %></td>
        <td><%= best_in_place apartment, :base_price, :as => :input %></td>
        <td><%= best_in_place apartment, :colour, :as => :input %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<br>
<button onclick="myFunction()">Update Caclculated fields</button>

</div>
<script>
function myFunction() {
    location.reload();
}
</script>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apartmentid:</strong>
  <%= @apartment.apartmentID %>
</p>

<p>
  <strong>Apartment type:</strong>
  <%= @apartment.apartment_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Internal area:</strong>
  <%= @apartment.internal_area %>
</p>

<p>
  <strong>Balcony area:</strong>
  <%= @apartment.balcony_area %>
</p>

<p>
  <strong>Total area:</strong>
  <%= @apartment.total_area %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @apartment.bedrooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @apartment.bathrooms %>
</p>

<p>
  <strong>Study:</strong>
  <%= @apartment.study %>
</p>

<p>
  <strong>Carbays:</strong>
  <%= @apartment.carbays %>
</p>

<p>
  <strong>Base price:</strong>
  <%= @apartment.base_price %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @apartment.colour %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/temp.html.erb
 <% delete_old_data2
    getdataapartment %>
   <%  controller.redirect_to apartments_path   %>