config/routes.rb
Rails.application.routes.draw do
  resources :towers
  resources :podia
  resources :pricings
  resources :apartments
  resources :gparameters
  resources :salesmatrices
  match 'ap' => 'apartments#temp', via: [:get, :post]
  match 'del_all' => 'podia#del_all', via: [:get, :post]
  match 'del_all' => 'towers#del_all', via: [:get, :post]

root 'salesmatrices#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sales Matrix Builder</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
   
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
         
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">STEP 1 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Input basic data", new_salesmatrix_path %></li>
                <li><%= link_to "Set Global parameters", new_gparameter_path %></li>
            
               
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">STEP 2 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Apartment Specs", apartments_path %></li>
                <li><%= link_to "Pricing Specs", pricings_path %></li>
              
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">STEP 3 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Podium Floorplates", podia_path %></li>
               <li><%= link_to "Tower Floorplates", towers_path %></li>
              
              </ul>
            </li>
          </ul>
          
        </div><!--/.nav-collapse -->
      </div>
    </nav> 
   <br>
    <br>
     <br>
<%= yield %>





<!--<%= debug(params) if Rails.env.development? %>-->
</body>
</html>